# Generated by Django 4.1.7 on 2023-04-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_word_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('change_blog_title', "Peut changer le titre d'un billet de blog")]},
        ),
    ]
