# Generated by Django 4.1.7 on 2023-04-13 14:28

from django.db import migrations

def from_author_to_contributors(apps, schema_migration):
    blog = apps.get_model("blog", "blog")

    for blog in blog.objects.all():
        if blog.author:
            blog.contributors.add(blog.author, through_defaults={"contributions": "Auteur principal"})

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_author_blogcontributor_blog_contributors'),
    ]

    operations = [
        migrations.RunPython(from_author_to_contributors)
    ]
